version: 2
jobs:
  build:
    working_directory: ~/p2002
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: ubuntu:xenial
    steps:
      - run:
          name: Install Deps
          command: 'sudo  sudo add-apt-repository ppa:maarten-fonville/protobuf -y & apt-get update -qq && apt-get install -y -qq libprotobuf-dev protobuf-compiler gcc-4.8 g++-4.8 libmysqlclient-dev libperl-dev libboost-dev liblua5.1-0-dev zlib1g-dev uuid-dev libssl-dev build-essential make cmake git-core'
      - checkout
      - run:
          name: CMake Env
          command: 'cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=ON -DEQEMU_BUILD_LOGIN=ON'
      - run:
          name: Build Source
          command: 'make -j 2'
      - run:
          name: Test
          command: './bin/tests'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
                - nats3
